"""
Wavefront OBJ Format Exporter
=============================

Exports 3D meshes to Wavefront OBJ format with MTL material files.
Compatible with Blender, Maya, and most 3D software.

Author: Iván Vankov Fortanet
Email: fortanet2002@gmail.com
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from typing import Optional, Dict, List, Any, Union
from dataclasses import dataclass
from pathlib import Path
import time

from mesh_generator import Mesh3D
from physics_inference import PhysicsProperties


@dataclass
class OBJExportConfig:
    """Configuration for OBJ export."""
    include_normals: bool = True
    include_uvs: bool = True
    include_vertex_colors: bool = True
    flip_yz: bool = False  # Flip Y and Z axes for different coordinate systems
    scale: float = 1.0  # Scale factor for vertices
    precision: int = 6  # Decimal precision for vertex coordinates
    write_mtl: bool = True  # Write material file


class OBJExporter:
    """
    Export 3D meshes to Wavefront OBJ format.
    
    The OBJ format is a simple, widely-supported 3D model format
    that stores vertex positions, normals, texture coordinates,
    and face definitions.
    
    Example:
        >>> from mesh_generator import ShadowMeshGenerator
        >>> generator = ShadowMeshGenerator()
        >>> mesh = generator.generate(contour)
        >>> exporter = OBJExporter()
        >>> exporter.export(mesh, "output.obj")
    """
    
    def __init__(self, config: Optional[OBJExportConfig] = None):
        """
        Initialize OBJ exporter.
        
        Args:
            config: Export configuration
        """
        self.config = config or OBJExportConfig()
    
    def export(
        self,
        mesh: Mesh3D,
        filepath: Union[str, Path],
        physics_props: Optional[PhysicsProperties] = None,
        material_name: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Export mesh to OBJ file.
        
        Args:
            mesh: Mesh3D object to export
            filepath: Output file path (.obj extension)
            physics_props: Optional physics properties for material
            material_name: Optional material name override
            
        Returns:
            Dictionary with export metadata
        """
        start_time = time.perf_counter()
        filepath = Path(filepath)
        
        # Ensure .obj extension
        if filepath.suffix.lower() != '.obj':
            filepath = filepath.with_suffix('.obj')
        
        # Generate MTL filename
        mtl_filename = None
        if self.config.write_mtl and physics_props is not None:
            mtl_filename = filepath.stem + '.mtl'
        
        # Write OBJ file
        obj_content = self._generate_obj_content(mesh, mtl_filename, material_name)
        
        with open(filepath, 'w') as f:
            f.write(obj_content)
        
        # Write MTL file if needed
        mtl_filepath = None
        if mtl_filename and physics_props:
            mtl_filepath = filepath.parent / mtl_filename
            mtl_content = self._generate_mtl_content(physics_props, material_name)
            with open(mtl_filepath, 'w') as f:
                f.write(mtl_content)
        
        elapsed_ms = (time.perf_counter() - start_time) * 1000
        
        return {
            'filepath': str(filepath),
            'mtl_filepath': str(mtl_filepath) if mtl_filepath else None,
            'vertices_exported': mesh.n_vertices,
            'faces_exported': mesh.n_faces,
            'export_time_ms': elapsed_ms,
        }
    
    def _generate_obj_content(
        self,
        mesh: Mesh3D,
        mtl_filename: Optional[str],
        material_name: Optional[str],
    ) -> str:
        """Generate OBJ file content."""
        lines = []
        
        # Header
        lines.append("# Wavefront OBJ file")
        lines.append(f"# Generated by ShadowMesh 3D")
        lines.append(f"# Vertices: {mesh.n_vertices}")
        lines.append(f"# Faces: {mesh.n_faces}")
        lines.append("")
        
        # Material reference
        if mtl_filename:
            lines.append(f"mtllib {mtl_filename}")
            lines.append("")
        
        if material_name:
            lines.append(f"usemtl {material_name}")
            lines.append("")
        
        # Vertices
        fmt = f"{{:.{self.config.precision}f}}"
        for v in mesh.vertices:
            x, y, z = v * self.config.scale
            if self.config.flip_yz:
                y, z = z, y
            lines.append(f"v {fmt} {fmt} {fmt}".format(x, y, z))
        
        lines.append("")
        
        # Texture coordinates (UVs)
        if self.config.include_uvs and len(mesh.uvs) > 0:
            for uv in mesh.uvs:
                lines.append(f"vt {uv[0]:.6f} {uv[1]:.6f}")
            lines.append("")
        
        # Vertex normals
        if self.config.include_normals and len(mesh.normals) > 0:
            for n in mesh.normals:
                nx, ny, nz = n
                if self.config.flip_yz:
                    ny, nz = nz, ny
                lines.append(f"vn {fmt} {fmt} {fmt}".format(nx, ny, nz))
            lines.append("")
        
        # Vertex colors (as comment, some software supports this)
        if self.config.include_vertex_colors and mesh.vertex_colors is not None:
            lines.append("# Vertex colors")
            for i, c in enumerate(mesh.vertex_colors):
                lines.append(f"# vc {i+1} {c[0]:.4f} {c[1]:.4f} {c[2]:.4f}")
            lines.append("")
        
        # Faces
        has_uvs = self.config.include_uvs and len(mesh.uvs) > 0
        has_normals = self.config.include_normals and len(mesh.normals) > 0
        
        for face in mesh.faces:
            # OBJ uses 1-based indexing
            v1, v2, v3 = face + 1
            
            if has_uvs and has_normals:
                # v/vt/vn format
                lines.append(f"f {v1}/{v1}/{v1} {v2}/{v2}/{v2} {v3}/{v3}/{v3}")
            elif has_uvs:
                # v/vt format
                lines.append(f"f {v1}/{v1} {v2}/{v2} {v3}/{v3}")
            elif has_normals:
                # v//vn format
                lines.append(f"f {v1}//{v1} {v2}//{v2} {v3}//{v3}")
            else:
                # v format
                lines.append(f"f {v1} {v2} {v3}")
        
        return "\n".join(lines)
    
    def _generate_mtl_content(
        self,
        physics_props: PhysicsProperties,
        material_name: Optional[str],
    ) -> str:
        """Generate MTL (material) file content."""
        name = material_name or "shadow_material"
        
        lines = []
        lines.append("# Wavefront MTL file")
        lines.append(f"# Material properties inferred from shadow")
        lines.append("")
        
        lines.append(f"newmtl {name}")
        
        # Diffuse color based on material type
        color = self._material_type_to_color(physics_props.material_type)
        lines.append(f"Kd {color[0]:.4f} {color[1]:.4f} {color[2]:.4f}")
        
        # Ambient color (darker)
        ka = [c * 0.2 for c in color]
        lines.append(f"Ka {ka[0]:.4f} {ka[1]:.4f} {ka[2]:.4f}")
        
        # Specular color (white, reduced for matte materials)
        ks_intensity = 0.1 + physics_props.rigidity * 0.4
        lines.append(f"Ks {ks_intensity:.4f} {ks_intensity:.4f} {ks_intensity:.4f}")
        
        # Shininess based on rigidity
        ns = 10 + physics_props.rigidity * 90
        lines.append(f"Ns {ns:.1f}")
        
        # Transparency (opaque for now)
        lines.append("d 1.0")
        lines.append("Tr 0.0")
        
        # Illumination model
        lines.append("illum 2")
        
        # Physics properties as comments
        lines.append("")
        lines.append("# Physics Properties")
        lines.append(f"# Material Type: {physics_props.material_type.value}")
        lines.append(f"# Rigidity: {physics_props.rigidity:.3f}")
        lines.append(f"# Density: {physics_props.density:.1f} kg/m³")
        lines.append(f"# Mass: {physics_props.mass:.6f} kg")
        lines.append(f"# Young's Modulus: {physics_props.youngs_modulus:.2e} Pa")
        lines.append(f"# Friction: {physics_props.friction_coefficient:.3f}")
        lines.append(f"# Restitution: {physics_props.restitution:.3f}")
        
        return "\n".join(lines)
    
    def _material_type_to_color(self, material_type: Any) -> List[float]:
        """Convert material type to RGB color."""
        from physics_inference import MaterialType
        
        colors = {
            MaterialType.RIGID_SOLID: [0.7, 0.7, 0.75],    # Gray-blue (metal-like)
            MaterialType.SOFT_SOLID: [0.9, 0.6, 0.4],      # Orange (rubber-like)
            MaterialType.LIQUID: [0.3, 0.5, 0.9],          # Blue
            MaterialType.GRANULAR: [0.8, 0.7, 0.5],        # Tan
            MaterialType.GAS: [0.9, 0.9, 1.0],             # Very light blue
            MaterialType.UNKNOWN: [0.5, 0.5, 0.5],         # Gray
        }
        
        return colors.get(material_type, [0.5, 0.5, 0.5])
    
    def export_batch(
        self,
        meshes: List[Mesh3D],
        filepaths: List[Union[str, Path]],
        physics_props_list: Optional[List[PhysicsProperties]] = None,
    ) -> List[Dict[str, Any]]:
        """
        Export multiple meshes to OBJ files.
        
        Args:
            meshes: List of Mesh3D objects
            filepaths: List of output file paths
            physics_props_list: Optional list of physics properties
            
        Returns:
            List of export metadata dictionaries
        """
        results = []
        
        for i, (mesh, filepath) in enumerate(zip(meshes, filepaths)):
            props = physics_props_list[i] if physics_props_list else None
            result = self.export(mesh, filepath, props)
            results.append(result)
        
        return results


def import_obj(filepath: Union[str, Path]) -> Mesh3D:
    """
    Import mesh from OBJ file.
    
    Args:
        filepath: Path to OBJ file
        
    Returns:
        Mesh3D object
    """
    filepath = Path(filepath)
    
    vertices = []
    normals = []
    uvs = []
    faces = []
    
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            parts = line.split()
            if not parts:
                continue
            
            if parts[0] == 'v':
                # Vertex
                vertices.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif parts[0] == 'vn':
                # Normal
                normals.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif parts[0] == 'vt':
                # Texture coordinate
                uvs.append([float(parts[1]), float(parts[2])])
            elif parts[0] == 'f':
                # Face
                face = []
                for part in parts[1:]:
                    # Handle v/vt/vn format
                    indices = part.split('/')
                    face.append(int(indices[0]) - 1)  # Convert to 0-based
                faces.append(face[:3])  # Only triangles
    
    # Convert to numpy arrays
    vertices = np.array(vertices, dtype=np.float32) if vertices else np.zeros((0, 3), dtype=np.float32)
    faces = np.array(faces, dtype=np.int32) if faces else np.zeros((0, 3), dtype=np.int32)
    
    if normals:
        normals = np.array(normals, dtype=np.float32)
    else:
        normals = np.zeros_like(vertices)
    
    if uvs:
        uvs = np.array(uvs, dtype=np.float32)
    else:
        uvs = np.zeros((len(vertices), 2), dtype=np.float32)
    
    return Mesh3D(
        vertices=vertices,
        faces=faces,
        normals=normals,
        uvs=uvs,
        metadata={'source': str(filepath)}
    )


def benchmark_obj_export():
    """Benchmark OBJ export performance."""
    import time
    from mesh_generator import ShadowMeshGenerator
    
    print("=" * 60)
    print("OBJ EXPORT BENCHMARK")
    print("=" * 60)
    
    # Generate test mesh
    generator = ShadowMeshGenerator()
    theta = np.linspace(0, 2 * np.pi, 64, endpoint=False)
    contour = np.column_stack([
        0.05 * np.cos(theta),
        0.05 * np.sin(theta)
    ]).astype(np.float32)
    mesh = generator.generate(contour)
    
    # Create physics properties
    from physics_inference import PhysicsProperties, MaterialType
    physics = PhysicsProperties(
        material_type=MaterialType.RIGID_SOLID,
        rigidity=0.9,
        youngs_modulus=70e9,
        density=2700.0,
        mass=0.1,
        volume=0.0001,
        friction_coefficient=0.3,
        restitution=0.5,
        confidence=0.85,
    )
    
    exporter = OBJExporter()
    
    # Warm-up
    for _ in range(10):
        exporter.export(mesh, "/tmp/test.obj", physics)
    
    # Benchmark
    n_iterations = 100
    start = time.perf_counter()
    
    for _ in range(n_iterations):
        exporter.export(mesh, "/tmp/test.obj", physics)
    
    elapsed_ms = (time.perf_counter() - start) * 1000
    latency = elapsed_ms / n_iterations
    
    print(f"\nMesh: {mesh.n_vertices} vertices, {mesh.n_faces} faces")
    print(f"Export time: {latency:.3f}ms")
    print(f"Throughput: {n_iterations/elapsed_ms*1000:.0f} exports/sec")
    
    print("\n" + "=" * 60)


if __name__ == "__main__":
    benchmark_obj_export()
